### ISSUE TITLE
Question: Megamodes 250mb limit?

### ISSUE THREAD

**Issue by thepry** [tongueroo/jets#108]
Jets looks very nice. You're making a great job!

I've just tried to deploy (development) a quite simple rails app and hit 250mb limit. But the doc states that there is 512 MB limit for a rails app.

```
=> Replacing compiled gems with AWS Lambda Linux compiled versions.
Checking projects gems for pre-built Lambda gems...
Gem nokogiri-1.9.1 unpacked at /tmp/jets/jets5app/stage/code
Gem pg-1.1.3 unpacked at /tmp/jets/jets5app/stage/code
=> rsync -a --links /tmp/jets/jets5app/stage/code/opt/ruby/gems/2.5.0/ /tmp/jets/jets5app/stage/code/vendor/gems/ruby/2.5.0/
Tidying project: removing ignored files to reduce package size.
Over the Lambda size limit of 250MB
Please reduce the size of your code.
Sizes:
Code: 71.2MB - /tmp/jets/jets5app/stage/code
Gem Layer: 218.9MB - /tmp/jets/jets5app/stage/opt
Total Package: 290.2MB
Over limit by: 40.2MB
```

```
rvm, 2.5.3
jets 1.3.9
```
I had 30mb bootsnap cache in rack/tmp folder. So after I removed it I was able to deploy it, but it looks like there is barely enough space for an empty rails application. Not sure that a real production project will fit in that limit.

Is there a workaround for this issue, that I can use?

**Comment by tongueroo** [comment]
> RE: Jets looks very nice. You're making a great job!

Thanks for the kind words. Really appreciate it! 😁

So before official Ruby support, the Rails application would load into `tmp`. Accidentally, didn't port logic that over 🤦🏻‍♂️  The old docs are still inaccurate in a few ways. This is all fixed in the v1.4.0 release [CHANGELOG](https://github.com/tongueroo/jets/blob/master/CHANGELOG.md).  

With the fix, the app code loads into `tmp` giving us more space buffer. 

Just deployed a test Rails app and it adds up to about 146M now. So we have a 104M buffer for additional gems.  Remember your code size will be very small since it is loaded into `tmp` properly now. The Tidying of the gems was not properly happening before also 🤦🏻‍♂️  This is also fixed. Gems are being tidied properly now and it saves more space.  Here's an example:

    $ du -csh /tmp/jets/demo-rails/stage/*
     80K    /tmp/jets/demo-rails/stage/code
    146M    /tmp/jets/demo-rails/stage/opt
    146M    total
    $ 

Unless you have 104MB of additional gems on top of the baseline necessary Rails gems, you should be good. If we get past this limit, got some ideas, just need time to implement them though. Also, think that AWS Lambda will ultimately increase the limit. 🤔  

Finally, there's an improved version of [Rails Support](http://rubyonjets.com/docs/rails-support/). It is vastly more straightforward, and I recommend using that. 👍

Closing this issue out to keep things tidy.
