### ISSUE TITLE
Actioncable with Rails?

### ISSUE THREAD

**Issue by nbarthel** [tongueroo/jets#200]
## Summary

I may be missing this in the docs, but is there a way to get Actioncable working?  I know API Gateway now supports websockets, with some caveats of course.

## Motivation

We use Actioncable for updates from the API to a JS front-end.  It's a deal-breaker in moving our API towards Lambda.

## Drawbacks

Requires a separate API Gateway instance.

## Unresolved Questions

I'm using Afterburner currently, would it be easier to move to Mega mode if I need it?

**Comment by tongueroo** [comment]
> RE: I may be missing this in the docs, but is there a way to get Actioncable working?

Don't think you're missing anything. Currently, it's not supported. Would like to figure it out in time.

🤔 Don’t think ActionCable will work with Restful API Gateway and Lambda (what Jets currently uses) because once the request is completed the connection gets closed. Will have to dig into Websocket API Gateway and see if that is possible to connect it to ActionCable's interface or make it behave similarly. Unsure when.

> RE: I'm using Afterburner currently, would it be easier to move to Mega mode if I need it?

Nope don’t think it’ll make a difference. Afterburner and Mega Mode underneath the hood work the same way. When the request completed with a normal restful API Gateway, the connection will be closed.

**Comment by nbarthel** [comment]
Just a final note on this.  It is definitely doable, but would require creating a separate peer API Gateway in Cloudformation.  I may tackle it and submit a PR.  Thanks for the quick response.  Great stuff!

**Comment by MilesRomney** [comment]
https://aws.amazon.com/blogs/compute/announcing-websocket-apis-in-amazon-api-gateway/
