### ISSUE TITLE
jets build fails for new project

### ISSUE THREAD

**Issue by undefinedvalue** [tongueroo/jets#215]
## Checklist

- [x] Upgrade Jets: Are you using the latest version of Jets? This allows Jets to fix issues fast. There's a `jets upgrade` command that makes this a simple task. There's also an Upgrading Guide: http://rubyonjets.com/docs/upgrading/
- [x] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.rubyonjets.com
- [x] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System |    OSX 10.13.4     |
| Jets             |    1.8.8     |
| Ruby             |    2.5.3     |

---

## Expected Behaviour

A newly created Jets project should build successfully.

## Current Behavior

A newly created Jets project fails to build due to webpack errors.

Here is the output of `jets build`
[err.txt](https://github.com/tongueroo/jets/files/2934979/err.txt)

## Step-by-step reproduction instructions

```
gem install jets
nvm install 8.10.0
nvm alias default node
npm install -g yarn
jets new --no-database demo
cd demo
jets build
```

**Comment by tongueroo** [comment]
@undefinedvalue Thanks for the report. This was an important one. Release fix in [v1.8.9](https://github.com/tongueroo/jets/blob/master/CHANGELOG.md)

Had to dig into this one a bit. Some notes for posterity:

* Webpacker upgraded to a newer version of babel.
* Looks like babel renamed a few of its libraries to be under the @babel namespace. IE: `syntax-dynamic-import` -> `@babel/plugin-syntax-dynamic-import`. So needed to update the generated [.babelrc](https://github.com/tongueroo/webpacker/blob/jets/lib/install/config/.babelrc) file to the new libraries.
* The `postcss-cssnext` plugin was also moved to a separate library. So that needed to be added as part of the `jets new` process.
* Webpacker also change the default behavior so that css files do not get compiled. You must now turn it on with `extract_css: true` in your `webpacker.yml`

Pushed out a release to fix this quickly.  Would like to revisit the webpacker fork when got time. Unsure when. Will consider PRs.
