### ISSUE TITLE
Feature request - allow to return a file as the API response

### ISSUE THREAD

**Issue by bartblast** [tongueroo/jets#220]
## Summary

Allow to return a file as the API response.

## Motivation

At the moment there is no way to return a file (for example a 1x1 tracking pixel).

**Comment by bartblast** [comment]
A workaround is a redirect call at the end of the action, e.g.
redirect_to "https://example.com/abc.gif"

**Comment by tongueroo** [comment]
Glad you were able to figure out a workaround.

Sure be able to render a file with `render file:`. The jets internal [public_controller.rb](https://github.com/tongueroo/jets/blob/master/lib/jets/internal/app/controllers/jets/public_controller.rb) uses this.

Note, binary images are a little tricky since it depends on the client sending specific accept headers, here's a discussion: https://forums.aws.amazon.com/thread.jspa?threadID=246629  Probably better to serve the image out of s3 anyway. Unsure, how to do something like a tracking pixel though.

**Comment by bartblast** [comment]
Yeah, initially I tried to replicate the way images are served from the public dir and actually I found the public controller - I tried many different scenarios, but nothing worked.
