### ISSUE TITLE
Jets app not working on deployment

### ISSUE THREAD

**Issue by cpobremaximiliandigital** [tongueroo/jets#367]
## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System |  10.13.6 (OSX High Sierra)  |
| Jets             |  2.1.7 |
| Ruby             |  2.5.1  |

---

## Expected Behaviour

I should be able to invoke a function on AWS Lambda Console.

## Current Behavior

It was causing an `Internal Server Error` from my end when invoking the deployed Jets app. Here's the screenshot:
![Screen Shot 2019-09-10 at 10 04 35 AM](https://user-images.githubusercontent.com/26074937/64578627-904b3c80-d3b2-11e9-90ef-ded49a8b19f6.png)

## Step-by-step reproduction instructions

- Run `jets deploy`
- Open the provided API Gateway Endpoint on a browser
- You'll see the Internal Server Error (check Cloudwatch logs)
- Open Lambda function and invoke it via Test (Internal Server Error again)

**Comment by tongueroo** [comment]
Unsure. Unable to reproduce. The error shows that it cannot:

> require "active_support"

On line 2. That's where it `require "jets"` gets called by the Jets handler shims.  Example:

```ruby
require "bundler/setup"
require "jets"
Jets.once  # runs once in lambda execution context
```

Some guesses:

* Maybe a system or project-specific bundler configuration is affecting the zipfile that Jets creates so that the gems are not being loaded by bundler correctly in Lambda.
* Check your project folder for `.bundle` folder and remove it if it exists.
* Check your local env for any `BUNDLE*` env var in case those are interfering. IE: `env | grep BUNDLE`. Remove them if they exists.

If this can be reproduced on another machine also, then that would be very helpful. One suggestion is to try it on a [fresh Cloud9 server](https://rubyonjets.com/docs/faster-development/). If it's reproduced there, then we know it's not system-specific.  If this is not just a newly generated project, then an example project will also help. 

Haven't seen this one before so am interested in what the issue, but will close out until there are more details.
