### ISSUE TITLE
Jets deploy deleted and created new API Gateway

### ISSUE THREAD

**Issue by ChrisBr** [tongueroo/jets#389]
This issue is probably hard to reproduce but still opening to get some feedback how we can investigate what's going on.

After updating Puma (probably unrelated but anyway documenting), the deployment of our Jets app created a new API Gateway which created a new URL as well. 

Logs from the deployment:
```
Deploying CloudFormation stack with jets app!
02:58:13PM UPDATE_IN_PROGRESS AWS::CloudFormation::Stack api-prod User Initiated
02:58:17PM UPDATE_IN_PROGRESS AWS::CloudFormation::Stack ApiGateway 
02:58:19PM UPDATE_IN_PROGRESS AWS::Lambda::LayerVersion GemLayer Requested update requires the creation of a new physical resource; hence creating one.
02:58:28PM UPDATE_COMPLETE AWS::CloudFormation::Stack ApiGateway 
02:58:30PM UPDATE_IN_PROGRESS AWS::Lambda::LayerVersion GemLayer Resource creation Initiated
02:58:30PM UPDATE_COMPLETE AWS::Lambda::LayerVersion GemLayer 
02:58:30PM CREATE_IN_PROGRESS AWS::CloudFormation::Stack ApiResources1 
02:58:30PM CREATE_IN_PROGRESS AWS::CloudFormation::Stack ApiResources1 Resource creation Initiated
02:58:32PM UPDATE_IN_PROGRESS AWS::CloudFormation::Stack JetsPreheatJob 
02:58:41PM CREATE_COMPLETE AWS::CloudFormation::Stack ApiResources1 
02:58:43PM UPDATE_IN_PROGRESS AWS::CloudFormation::Stack RecipesController 
02:58:43PM UPDATE_IN_PROGRESS AWS::CloudFormation::Stack KeywordsController 
02:58:54PM UPDATE_COMPLETE AWS::CloudFormation::Stack JetsPreheatJob 
02:59:18PM UPDATE_COMPLETE AWS::CloudFormation::Stack KeywordsController 
02:59:18PM UPDATE_COMPLETE AWS::CloudFormation::Stack RecipesController 
02:59:20PM CREATE_IN_PROGRESS AWS::CloudFormation::Stack ApiDeployment20191002145808 
02:59:20PM CREATE_IN_PROGRESS AWS::CloudFormation::Stack ApiDeployment20191002145808 Resource creation Initiated
02:59:31PM CREATE_COMPLETE AWS::CloudFormation::Stack ApiDeployment20191002145808 
02:59:33PM UPDATE_COMPLETE_CLEANUP_IN_PROGRESS AWS::CloudFormation::Stack api-prod 
02:59:34PM UPDATE_IN_PROGRESS AWS::CloudFormation::Stack KeywordsController 
02:59:34PM UPDATE_IN_PROGRESS AWS::CloudFormation::Stack RecipesController 
02:59:34PM DELETE_IN_PROGRESS AWS::CloudFormation::Stack ApiDeployment20190828115917 
02:59:34PM UPDATE_IN_PROGRESS AWS::CloudFormation::Stack JetsPreheatJob 
02:59:44PM UPDATE_COMPLETE AWS::CloudFormation::Stack JetsPreheatJob 
02:59:45PM DELETE_COMPLETE AWS::CloudFormation::Stack ApiDeployment20190828115917 
02:59:55PM UPDATE_COMPLETE AWS::CloudFormation::Stack KeywordsController 
02:59:56PM UPDATE_COMPLETE AWS::CloudFormation::Stack RecipesController 
02:59:56PM UPDATE_IN_PROGRESS AWS::CloudFormation::Stack ApiGateway 
02:59:56PM DELETE_IN_PROGRESS AWS::Lambda::LayerVersion GemLayer 
02:59:58PM DELETE_COMPLETE AWS::Lambda::LayerVersion GemLayer 
03:00:07PM UPDATE_COMPLETE AWS::CloudFormation::Stack ApiGateway 
03:00:07PM UPDATE_COMPLETE AWS::CloudFormation::Stack api-prod 
Stack success status: UPDATE_COMPLETE
Time took for stack deployment: 1m 55s.
Prewarming application.
API Gateway Endpoint: https://123456789.execute-api.us-east-1.amazonaws.com/prod/
```

@tongueroo is there anything you think could've triggered this behaviour? Happy to provide more information but it's quite hard to debug and find out what was going on there. Maybe you can give me some leads. Thanks

**Comment by tongueroo** [comment]
Yes. Puma is unrelated.

Jets can possibly delete and recreate the REST API. This is documented behavior in [Custom Domain](https://rubyonjets.com/docs/routing/custom-domain/) under "Routes Deployment"

> Jets does what is necessary to deploy route changes. Sometimes this requires replacing the Rest API entirely. Jets detects this and will create a brand new Rest API when needed. This is one of the reasons why a Custom Domain is recommended to be set up, so the endpoint url remains the same.

It's also mentioned in this Community Discussion [Jets deploy: CREATE_FAILED AWS::CloudFormation::Stack ApiGateway Embedded 
](https://community.rubyonjets.com/t/jets-deploy-create-failed-aws-stack-apigateway-embedded/52/8?u=tung)

Jets computes and figures out whether or not it needs to replace the REST API as part of deployment: [Routes Change Detection](https://github.com/tongueroo/jets/blob/master/lib/jets/resource/api_gateway/rest_api/routes/change.rb#L9). 

Jets does this because it is sometimes the only way to deploy successfully.  Otherwise, the CloudFormation stacks rollback.  

For example, let's say you change a route path to point to a new controller action. As simple as that sounds. It causes a rollback. Understanding the CloudFromation process helps explain:

Create new Rest API Resource with the existing path
Detects that it already exists
Errors and rolls back the stack

So, Jets automates what you would manually have to do normally. IE: manually create a new API Gateway and then switch over to it. 

Suggest that you use a [Custom Domain](https://rubyonjets.com/docs/routing/custom-domain/). For production services, I usually also front the custom domain with a CloudFront CDN for more DNS control.

**Comment by andrassy** [comment]
Makes sense. We have a slightly complex scenario in that the APIGateway is private but granted resource control access from another AWS account via a Service Endpoint. DNS alias won’t really work here as the gateway ID would have to be passed as a header anyway for the resolution to happen properly. :(

**Comment by tongueroo** [comment]
Interesting. Unsure if even a Private Hosted Zone with Private DNS would work there as there are 2 AWS accounts involved. 🤔

Found this: [Associating an Amazon VPC and a Private Hosted Zone That You Created with Different AWS Accounts](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/hosted-zone-private-associate-vpcs-different-accounts.html)  Looks a Private Hosted Zone can be associated with another AWS account on a VPC. Unsure if that 'll help with your situation. 🧐

**Comment by andrassy** [comment]
Ah thanks for that. We’ll explore and update here.

**Comment by ChrisBr** [comment]
@tongueroo thanks for the detailed response 👍 

I have two suggestions:

1) What do you think about adding logging for this in the deployment?

2) In the case you don't setup a custom domain, this operation is destructive. Would you be fine in introducing an option to not delete the old Lambda function and API Gateway. In our case, for instance we would need to manually do an green/blue deployment so it would be desired to e.g. fail in this case or leave the old function running and just deploy a new one and then manually cleanup after we executed the red/blue deploy (in our case, pointing our circuit breakers to the new URL).
