### ISSUE TITLE
AWS region not being honored

### ISSUE THREAD

**Issue by KevinColemanInc** [tongueroo/jets#403]
## Checklist

- [x] Upgrade Jets: Are you using the latest version of Jets? This allows Jets to fix issues fast. There's a `jets upgrade` command that makes this a simple task. There's also an Upgrading Guide: http://rubyonjets.com/docs/upgrading/
- [x ] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.rubyonjets.com
- [x] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System |     OSX    |
| Jets             |    2.3.4     |
| Ruby             |    2.5.7     |

---

## Expected Behaviour

The developer guide / deploy guides should show you how to honor the region in AWS

https://rubyonjets.com/quick-start/
https://rubyonjets.com/reference/jets-deploy/

## Current Behavior

If you follow the developer guide, you will see that the jets defaults to us-east-1 instead of what is defined in the `~/.aws/config` file like the `jets-deploy` says it should.

### Pre-test
Make sure that the `aws` cli app is NOT installed or at least not in your PATH. You can verify this 

```
git:(master) ✗ aws configure get region
zsh: command not found: aws
```

### Test
Setup the `~/.aws/config` as described [in the docs](https://rubyonjets.com/docs/deploy/)
Run the deploy command. It will use `us-east-1`

## Code Sample

You can see if the `aws` cli isn't installed it skips over the config:

https://github.com/tongueroo/jets/blob/112d9ff4f91c4dafc160d63371f15aaaafe0ec89/lib/jets/aws_info.rb#L17

## Solution Suggestion

Either update the docs to say the CLI is required or don't call the `aws` cli tool (preferred, b/c you don't need to start another process just to read from a text file).

**Comment by gokaykucuk** [comment]
What should be the expected behaviour if there is no AWS CLI installed and no ~/.aws/config is found? Should the deployment fail or just go ahead and deploy on us-east-1? 

Maybe we can deploy it on us-east-1 and then display a message to notify the user about this?

**Comment by KevinColemanInc** [comment]
> What should be the expected behaviour if there is no AWS CLI installed and no ~/.aws/config is found?

I don't have a strong opinion about this. 

My problem is that the docs say to add `~/.aws/config` but then don't honor what is in the file if the cli isn't installed. This doesn't make sense because the docs don't say the AWS client is required. I think you should either:

1. require the AWS client to be installed
2. Use ruby to directly read from that file instead of starting up another process (making your deploy slower).

**Comment by gokaykucuk** [comment]
I have just 1 problem with the second option, if there any are other parts of Jets, which also depend on AWS CLI being installed(maybe @tongueroo can chime in)? Because if so, then updating the docs to require AWS CLI makes more sense. Either way we can make a small PR on it.

**Comment by KevinColemanInc** [comment]
I would update the docs and the code:
https://github.com/tongueroo/jets/blob/112d9ff4f91c4dafc160d63371f15aaaafe0ec89/lib/jets/aws_info.rb#L17

This should be throwing an error if the client isn't present. It seems like the intention was for it to be optional (based on the code and preceding comment).

**Comment by tongueroo** [comment]
> RE: AWS region not being honored

Dug into this. Unable to reproduce. Was able to deploy to different regions with different aws profiles in `~/.aws/config`:

    $ AWS_PROFILE=tung-west aws configure get region
    us-west-2
    $ AWS_PROFILE=tung-east aws configure get region                                                        
    us-east-1
    $ 
    
    $ AWS_PROFILE=tung-east jets deploy
    ...
    $ AWS_PROFILE=tung-east jets url
    API Gateway Endpoint: https://0m17ffdv9l.execute-api.us-east-1.amazonaws.com/dev
    $ AWS_PROFILE=tung-west jets deploy
    ...
    $ AWS_PROFILE=tung-west jets url                                                                        
    API Gateway Endpoint: https://ui6ce467hc.execute-api.us-west-2.amazonaws.com/dev
    $ 

    $ AWS_PROFILE=tung-east aws apigateway get-rest-apis
    {
        "items": [
            {
                "id": "0m17ffdv9l",
                "name": "demo-dev",
                "createdDate": 1577135079,
                "binaryMediaTypes": [
                    "multipart/form-data"
                ],
                "apiKeySource": "HEADER",
                "endpointConfiguration": {
                    "types": [
                        "EDGE"
                    ]
                }
            }
        ]
    }
    $ AWS_PROFILE=tung-west aws apigateway get-rest-apis
    {
        "items": [
            {
                "id": "ui6ce467hc",
                "name": "demo-dev",
                "createdDate": 1577134926,
                "binaryMediaTypes": [
                    "multipart/form-data"
                ],
                "apiKeySource": "HEADER",
                "endpointConfiguration": {
                    "types": [
                        "EDGE"
                    ]
                }
            }
        ]
    }
    $     


Details of jets deploy: https://gist.github.com/tongueroo/7b244c11c27ec882c9bb17c9d73af00f

Wondering if `AWS_REGION` might be set?  When it is set, it takes higher precedence than what's in `~/.aws/config`.  https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html#config-settings-and-precedence  So then it would always deploy to the same region, regardless of what's in ~/.aws/config.

It's actually a useful way to deploy to multiple regions without having to create another AWS_PROFILE. IE:

    AWS_REGION=us-east-1 jets deploy
    AWS_REGION=us-west-2 jets deploy
    
> RE: require the AWS client to be installed

Yes. There are places where jets calls shells out to the `aws cli`. Would like to make it optional. Thought it was working. Unsure if it's worth the time.  Think will just update the docs to say install it to move on. 

> RE: Use ruby to directly read from that file instead of starting up another process (making your deploy slower).

Sure. Not shelling out to the aws cil is preferable. Will consider a PR for it.

Tip: Used [a2ikm/aws_config](https://github.com/a2ikm/aws_config) in the [tongueroo/aws-mfa-secure](https://github.com/tongueroo/aws-mfa-secure) gem achieve this there.  So that's how it would be done. But in the aws-mfa-secure gem itself, it shells out as a trick to grab temporary credentials because the gem itself overrides aws-sdk-core credentials logic to achieve what it needs to do. FWIW, the aws-mfa-secure decoration logic only triggers if you actually configure your ~/.aws/config to use it. Both should probably be updated so that it doesn't shell out to the `aws cli` at all. Believe Jets is the easier one to update actually. Will consider PRs for both.

**Comment by KevinColemanInc** [comment]
@tongueroo 

```
$ AWS_PROFILE=tung-west aws configure get region
us-west-2
```

This should be returning:

```
command not found: aws
```

Once you have verified that `aws` cli is NOT installed, try running `jets deploy` and see which region it deploys to.

**Comment by tongueroo** [comment]
Oh I see. So the aws cli is not installed and jets doesn't respect the region because it fails on shelling out. Make sense. Cool, will just add a note to make sure aws cli is installed.

**Comment by KevinColemanInc** [comment]
Why not update the code too?

**Comment by tongueroo** [comment]
Sure. Will consider PRs. Otherwise will get to it in time. No sweat either way.
