### ISSUE TITLE
Application IAM roles ignored?

### ISSUE THREAD

**Issue by matiaskorhonen** [tongueroo/jets#68]
I have this at the end of the configure block in `application.rb`:

```rb
config.iam_policy = [
  *Jets::Application.default_iam_policy,
  {
    action: ["dynamodb:*"],
    effect: "Allow",
    resource: "arn:aws:dynamodb:#{Jets.aws.region}:#{Jets.aws.account}:table/#{Jets.project_namespace}-*",
  }
]
```

Yet this seems to have no effect on the IAM policy/roles that actually ends up on AWS. The policy created on AWS seems to be just the default IAM policy.

Am I doing something wrong or is this feature not working as intended?

**Comment by tongueroo** [comment]
@matiaskorhonen  Thanks for the report. 

> RE: Am I doing something wrong or is this feature not working as intended?

This was a bug. Fixed in #69 Released in v1.0.16 [Changelog](https://github.com/tongueroo/jets/blob/master/CHANGELOG.md)

Also updated the [IAM Policies docs](http://rubyonjets.com/docs/iam-policies/) to include a section on "Application-wide: Override but Keep Default"
