### ISSUE TITLE
Deploy failed. No such file or directory

### ISSUE THREAD

**Issue by s1140227** [tongueroo/jets#99]
I'm using
- rbenv, ruby 2.5.3
- jets 1.3.6
- bundler 1.17.2
    - global config 「BUNDLE_PATH: "vendor/bundle"」

Flow of reproduction
1. created Gemfile 「gem "jets"」in empty folder. And  `bundle install`
2. created skeleton jets project. `bundle exec jets new v1 --mode api`
3. `cd v1` 
4. `bundle exec jets deploy`

```
Tidying project: removing ignored files to reduce package size.
bundler: failed to load command: jets (/Users/user/Desktop/project/api/vendor/bundle/ruby/2.5.0/bin/jets)
Errno::ENOENT: No such file or directory @ rb_file_s_rename - (/tmp/jets/v1/stage/code/vendor/bundle/ruby/2.5.0, /tmp/jets/v1/stage/opt/ruby/gems/2.5.0)
  /Users/user/.rbenv/versions/2.5.3/lib/ruby/2.5.0/fileutils.rb:471:in `rename'
  /Users/user/.rbenv/versions/2.5.3/lib/ruby/2.5.0/fileutils.rb:471:in `block in mv'
  /Users/user/.rbenv/versions/2.5.3/lib/ruby/2.5.0/fileutils.rb:1463:in `block in fu_each_src_dest'
  /Users/user/.rbenv/versions/2.5.3/lib/ruby/2.5.0/fileutils.rb:1479:in `fu_each_src_dest0'
  /Users/user/.rbenv/versions/2.5.3/lib/ruby/2.5.0/fileutils.rb:1461:in `fu_each_src_dest'
  /Users/user/.rbenv/versions/2.5.3/lib/ruby/2.5.0/fileutils.rb:460:in `mv'
  /Users/user/Desktop/project/api/vendor/bundle/ruby/2.5.0/gems/jets-1.3.6/lib/jets/builders/lambda_layer.rb:34:in `move_vendor_to_opt'
  /Users/user/Desktop/project/api/vendor/bundle/ruby/2.5.0/gems/jets-1.3.6/lib/jets/builders/lambda_layer.rb:18:in `build'
  /Users/user/Desktop/project/api/vendor/bundle/ruby/2.5.0/gems/jets-1.3.6/lib/jets/builders/code_builder.rb:114:in `build_lambda_layer'
  /Users/user/Desktop/project/api/vendor/bundle/ruby/2.5.0/gems/jets-1.3.6/lib/jets/builders/code_builder.rb:104:in `code_finish'
  /Users/user/Desktop/project/api/vendor/bundle/ruby/2.5.0/gems/jets-1.3.6/lib/jets/builders/code_builder.rb:42:in `block in build'
  /Users/user/Desktop/project/api/vendor/bundle/ruby/2.5.0/gems/jets-1.3.6/lib/jets/builders/code_builder.rb:38:in `chdir'
  /Users/user/Desktop/project/api/vendor/bundle/ruby/2.5.0/gems/jets-1.3.6/lib/jets/builders/code_builder.rb:38:in `build'
  /Users/user/Desktop/project/api/vendor/bundle/ruby/2.5.0/gems/jets-1.3.6/lib/jets/commands/build.rb:26:in `build_code'
  /Users/user/Desktop/project/api/vendor/bundle/ruby/2.5.0/gems/jets-1.3.6/lib/jets/commands/deploy.rb:50:in `build_code'
  /Users/user/Desktop/project/api/vendor/bundle/ruby/2.5.0/gems/jets-1.3.6/lib/jets/commands/deploy.rb:29:in `run'
  /Users/user/Desktop/project/api/vendor/bundle/ruby/2.5.0/gems/jets-1.3.6/lib/jets/commands/main.rb:21:in `deploy'
  /Users/user/Desktop/project/api/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /Users/user/Desktop/project/api/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/user/Desktop/project/api/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /Users/user/Desktop/project/api/vendor/bundle/ruby/2.5.0/gems/jets-1.3.6/lib/jets/commands/base.rb:38:in `dispatch'
  /Users/user/Desktop/project/api/vendor/bundle/ruby/2.5.0/gems/jets-1.3.6/lib/jets/commands/base.rb:27:in `perform'
  /Users/user/Desktop/project/api/vendor/bundle/ruby/2.5.0/gems/jets-1.3.6/lib/jets/cli.rb:21:in `start'
  /Users/user/Desktop/project/api/vendor/bundle/ruby/2.5.0/gems/jets-1.3.6/lib/jets/cli.rb:5:in `start'
  /Users/user/Desktop/project/api/vendor/bundle/ruby/2.5.0/gems/jets-1.3.6/exe/jets:14:in `<top (required)>'
  /Users/user/Desktop/project/api/vendor/bundle/ruby/2.5.0/bin/jets:23:in `load'
  /Users/user/Desktop/project/api/vendor/bundle/ruby/2.5.0/bin/jets:23:in `<top (required)>'
```

When I comment out 'tidy' function,  deploy succeed.

https://github.com/tongueroo/jets/blob/master/lib/jets/builders/ruby_packager.rb#L31

**Comment by tongueroo** [comment]
Thanks for providing so much debugging details. Unbelievably, I was not still able to reproduce even with all of your great details. 🤦🏻‍♂️

Unsure why uncommenting out the call to `tidy` fixes it 🧐  The stack error says:

    Errno::ENOENT: No such file or directory @ rb_file_s_rename - (/tmp/jets/v1/stage/code/vendor/bundle/ruby/2.5.0, /tmp/jets/v1/stage/opt/ruby/gems/2.5.0)

So the complaint is about a missing folder, even though commented out tidy fixed the issue?

There's a call to created the destination parent directory: `FileUtils.mkdir_p(File.dirname(gems))`  here: https://github.com/tongueroo/jets/blob/40ee8bb36673fd4cb7f60837b13d28effe4977d0/lib/jets/builders/lambda_layer.rb#L33 So we know the destination folder exists. It seems like the source folder doesn't exist. Tried reproducing with the clues from the details above and no luck yet.

The bundler config gives me an idea though:

- bundler 1.17.2
    - global config 「BUNDLE_PATH: "vendor/bundle"」

Wondering since Jets bundles also to the `vendor/bundle`, if that somehow screws things up.  Wanted to avoid the possible collision anyway, so went ahead and moved the path where the gems get bundled into by Jets to `vendor/gems` instead in this PR #100.

Went for it and released it and am interested in seeing if this fixes this odd issue. Can you give Jets v1.3.7 [CHANGELOG](https://github.com/tongueroo/jets/blob/master/CHANGELOG.md) a try and see if it helps?  

If that does not work, can you try to unset your bundle config global BUNDLE_PATH value. Wondering if that is somehow related.

Could be completely on an incorrect path here also. Still unsure why commenting out tidy for you fixed the issue. 🤔  Thanks for helping.

**Comment by tongueroo** [comment]
So read through the issue again. This stood out.

    bundler: failed to load command: jets (/Users/user/Desktop/project/api/vendor/bundle/ruby/2.5.0/bin/jets)

Thinking that by moving the bundling of the gems from `vendor/bundle` to `vendor/gems` in #100 In theory, this should fix it.  Let's see. Interested to see when you get a chance to test it out. Thanks!

**Comment by tongueroo** [comment]
Closing this out to keep tickets tidy. Feel free to open if it's still an issue.

**Comment by s1140227** [comment]
@tongueroo 
Thank you for quick response!
I recreated projects by 'jets 1.4.0' but, have another error message.

```
Bundle complete! 8 Gemfile dependencies, 52 gems now installed.
Gems in the groups development and test were not installed.
Bundled gems are installed into `/tmp/jets/v1/cache/vendor/gems`
Bundle install success.
Tidying project: removing ignored files to reduce package size.
=> rsync -a --links /tmp/jets/v1/stage/code/vendor/gems/ruby/2.5.0/ /tmp/jets/v1/stage/opt/ruby/gems/2.5.0/
rsync: link_stat "/tmp/jets/v1/stage/code/vendor/gems/ruby/2.5.0/." failed: No such file or directory (2)
rsync error: some files could not be transferred (code 23) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52.200.1/rsync/main.c(996) [sender=2.6.9]
rsync -a --links /tmp/jets/v1/stage/code/vendor/gems/ruby/2.5.0/ /tmp/jets/v1/stage/opt/ruby/gems/2.5.0/ failed to run.
/Users/uxmobile/Desktop/sasry-server/api/vendor/bundle/ruby/2.5.0/gems/jets-1.4.0/lib/jets/builders/lambda_layer.rb:33:in `rsync_and_link'
```

Is this case, folder permission?
- `tmp/jets/v1/cache`  directory is complete bundle installed.
- `tmp/jets/v1/stage/code/vendor` directory is empty.
- `tmp/jets/v1/stage/opt/ruby/gems/2.5.0` directory is empty.

I forgot to write it.
- OS: mac OS Mojave 10.14.2

**Comment by tongueroo** [comment]
@s1140227 Thanks for debugging info! 👍

Wondering what's in the `/tmp/jets/v1/cache` folder?

It's weird that both `/tmp/jets/v1/stage/code/vendor` and `/tmp/jets/v1/stage/opt/ruby/gems/2.5.0` are both empty. This seems to indicate the `/tmp/jets/v1/cache/vendor/gems` might not exist. 

Jets copies the gems from `/tmp/jets/v1/cache/vendor/gems` to `/tmp/jets/v1/stage/code/vendor/gems` earlier in the process before later moving things around and setting up the structure for AWS Lambda.

https://github.com/tongueroo/jets/blob/master/lib/jets/builders/ruby_packager.rb#L172-L175

You can see that it will only copy the `vendor/gems` folder though if it exists. So wondering what's in the `/tmp/jets/v1/cache` folder.

**Comment by s1140227** [comment]
@tongueroo Thank you for your reply!

`/tmp/jets/v1/cache` include

- .bundle
- Gemfile
- Gemfile.lock
- vendor/gems/ruby/2.5.0/... (bin, build_info, cache, doc, extensions, gems, specifications)

The list of gem files is different.

#### /tmp/jets/v1/cache/vendor/gems/ruby/2.5.0/gems/

```
actionpack-5.2.2		aws-sdk-sqs-1.10.0		mimemagic-0.3.3
actionview-5.2.2		aws-sigv4-1.0.3			mini_portile2-2.4.0
activemodel-5.2.2		builder-3.2.3			minitest-5.11.3
activerecord-5.2.2		colorize-0.8.1			mysql2-0.5.2
activesupport-5.2.2		concurrent-ruby-1.1.4		nokogiri-1.9.1
arel-9.0.0			crass-1.0.4			rack-2.0.6
aws-eventstream-1.0.1		dotenv-2.5.0			rack-test-1.1.0
aws-partitions-1.127.0		erubi-1.8.0			rails-dom-testing-2.0.3
aws-sdk-apigateway-1.23.0	gems-1.1.1			rails-html-sanitizer-1.0.4
aws-sdk-cloudformation-1.14.0	hashie-3.6.0			railties-5.2.2
aws-sdk-cloudwatchlogs-1.12.0	i18n-1.3.0			rake-12.3.2
aws-sdk-core-3.44.1		jets-1.4.0			recursive-open-struct-1.1.0
aws-sdk-dynamodb-1.19.0		jmespath-1.4.0			text-table-1.2.4
aws-sdk-kms-1.13.0		kramdown-1.17.0			thor-0.20.3
aws-sdk-lambda-1.16.0		loofah-2.2.3			thread_safe-0.3.6
aws-sdk-s3-1.30.0		memoist-0.16.0			tzinfo-1.2.5
aws-sdk-sns-1.9.0		method_source-0.9.2
```

#### /Users/user/Desktop/project/api/vendor/bundle/ruby/2.5.0/gems

```
actionpack-5.2.2		capybara-3.12.0			nokogiri-1.9.1
actionview-5.2.2		colorize-0.8.1			public_suffix-3.0.3
activemodel-5.2.2		concurrent-ruby-1.1.4		rack-2.0.6
activerecord-5.2.2		crass-1.0.4			rack-test-1.1.0
activesupport-5.2.2		diff-lcs-1.3			rails-dom-testing-2.0.3
addressable-2.5.2		dotenv-2.5.0			rails-html-sanitizer-1.0.4
arel-9.0.0			erubi-1.8.0			railties-5.2.2
aws-eventstream-1.0.1		gems-1.1.1			rake-12.3.2
aws-partitions-1.127.0		hashie-3.6.0			recursive-open-struct-1.1.0
aws-sdk-apigateway-1.23.0	i18n-1.3.0			regexp_parser-1.3.0
aws-sdk-cloudformation-1.14.0	jets-1.4.0			rspec-3.8.0
aws-sdk-cloudwatchlogs-1.12.0	jmespath-1.4.0			rspec-core-3.8.0
aws-sdk-core-3.44.1		kramdown-1.17.0			rspec-expectations-3.8.2
aws-sdk-dynamodb-1.19.0		launchy-2.4.3			rspec-mocks-3.8.0
aws-sdk-kms-1.13.0		loofah-2.2.3			rspec-support-3.8.0
aws-sdk-lambda-1.16.0		memoist-0.16.0			shotgun-0.9.2
aws-sdk-s3-1.30.0		method_source-0.9.2		text-table-1.2.4
aws-sdk-sns-1.9.0		mimemagic-0.3.3			thor-0.20.3
aws-sdk-sqs-1.10.0		mini_mime-1.0.1			thread_safe-0.3.6
aws-sigv4-1.0.3			mini_portile2-2.4.0		tzinfo-1.2.5
builder-3.2.3			minitest-5.11.3			xpath-3.2.0
byebug-10.0.2			mysql2-0.5.2
```

**Comment by tongueroo** [comment]
That's really strange that the list of gems is different. Think bundler is always installing them into current folders `vendor/bundle` vs in the cache area. So it seems like `BUNDLE_IGNORE_CONFIG` is  not working 😔

https://github.com/tongueroo/jets/blob/3e007d4dc853f1c3bdc679253862a9a728eb5854/lib/jets/builders/ruby_packager.rb#L57

Wondering if there is something funny with Jets and how bundler is set up on your environment. 🧐 Would like to see if we can eliminate your bundler environment. Wondering if you can you make a backup of your ~/.bundle folder.

     mv ~/.bundle ~/.bundle.backup

Then open up a new terminal and try a jets deploy with what I'm hoping is a completely clean bundler environment.

Would actually like to dig into the issue if it turns out that its the specific bundler environment on your setup. But let's see if we can eliminate it first.

When you're done just restore your bundler env:

    mv ~/.bundle.backup ~/.bundle

Also, can you post your `bundle env`? Thanks again for providing helpful debugging information, even though we haven't nailed this one down yet. 🤔

**Comment by tongueroo** [comment]
Oh duh. The gem list files should be different because jets runs `bundle install --without development test`. So a different gem list is a just [red herring](https://en.wikipedia.org/wiki/Red_herring).  

Anyway, let’s try a clean bundler environment.

**Comment by s1140227** [comment]
@tongueroo 
yep. my projects directory include development libs, but tmp directory not include.

I recreated project and, removed local bundler settings.
Deploy succeed!
Thank you your support.
